### ISSUE TITLE
[Issue#1][Функционал приложения] Завершение выполнения команды

### ISSUE THREAD

**Issue by Veleri** [yehormonko/TaskManagerMaven#1]
После завершения выполнения любой команды, пользователь должен попадать в главное меню приложения. Убрать вопрос "Return to menu? y/n" после каждой команды.

**Comment by yehorsyrin** [comment]
исправлено, убрано проверку выхода, оставлено только при выходе из программы и вопрос о желании отредактировать еще что то в задаче в пункте edit
