### ISSUE TITLE
[Issue#3][Логирование] Уровни логирования

### ISSUE THREAD

**Issue by Veleri** [yehormonko/TaskManagerMaven#12]
Логирование следует организовывать на уровнях: info, debug, error.

**Comment by yehorsyrin** [comment]
В комите Last part of Fixes установил уровень логирования info, который предусматривает записи и на остальных двух уровнях

**Comment by Veleri** [comment]
Не вижу уровня debug.

**Comment by Veleri** [comment]
Доработка сделана, номера коммита нет.
