### ISSUE TITLE
[Issue#1][Код] Перенести функционал контроллера в класс "Controller"

### ISSUE THREAD

**Issue by Veleri** [yehormonko/TaskManagerMaven#13]
По факту у тебя смешались понятия контролера и представления. Представление отвечает лишь за отображение информации пользователю, а у тебя класс "View"  также выполняет функцию контролера, а вот сам класс "Controller" содержит всего лишь несколько методов. Перенеси функционал, отвечающий за управление логики работы приложения, в класс "Controller", после этого будет видно, стоит ли представлению выделять класс или все же, представление реализовать в рамках контролера.

**Comment by yehorsyrin** [comment]
В комите  Fixed  был добавлен новый класс ViewController. Он совмещает методы и поля класса View и Controller, но они при этом пока не убраны

**Comment by Veleri** [comment]
Переименуй класс "ViewController" в "Controller" т.к. этот класс является не контроллером представления, а контроллером всего приложения. Также, верни пакет controller, который ты удалил и помести класс в соответствующий пакет.

**Comment by Veleri** [comment]
В комментариях не указан номер коммита и отметка об исправлении дефекта.
