### ISSUE TITLE
[Issue#3][Код] Добавление констант

### ISSUE THREAD

**Issue by Veleri** [yehormonko/TaskManagerMaven#15]
Все важные текстовые сообщения приложения вынеси в константы.

**Comment by yehorsyrin** [comment]
Пересмотрел переменные, не нашел таких, которые используются больше чем один раз в методе

**Comment by Veleri** [comment]
В константы можно выносить не только переменные, которые используются больше одного раза,  а и важные сообщения приложения.  Как минимум сообщение "would you like to change something else? y/n"" встречается 5 раз.
