### ISSUE TITLE
[Issue#5][Код] Switch-case: добавить break и удалить пустые return

### ISSUE THREAD

**Issue by Veleri** [yehormonko/TaskManagerMaven#17]
Не вижу в switch-case оператора "break" + вижу пустые "return". Использовать "return" нужно в том случае, если ты действительно возвращаешь какое-то значение.

**Comment by yehorsyrin** [comment]
В комите Second part of Fixes добавил в конструкции switch-case операторы "break". Оставил "return" в  методах, которые ничего не возвращают только там, где нужно гарантированное окончание работы метода

**Comment by Veleri** [comment]
if(list.size()==0) {
		System.out.println("no tasks");
		return;
	}
Зачем в данном случае использовать return? Ты просто выводишь на консоль значение "no tasks", при этом выхода из цикла или т.п. не происходит. "Return" лишний. Пересмотри код на такие "моменты".

**Comment by yehorsyrin** [comment]
Исправлено в Fourth part of Fixes
