### ISSUE TITLE
[Issue#6][Код] Пересмотреть переменые

### ISSUE THREAD

**Issue by Veleri** [yehormonko/TaskManagerMaven#18]
Вынеси все важные переменные, которыми ты неоднократно пользуешься в методах, в поля класса, или же подумай над местом их объявления. Ты часто объявляешь подобные переменные в разных методах, например это касается переменной: 
 - SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss.SS", Locale.ENGLISH);

**Comment by yehorsyrin** [comment]
В комите Second part of Fixes убрал лишние переменные, например 
SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss.SS", Locale.ENGLISH); объявляется лишь в методе для ввода дат inputDate
