### ISSUE TITLE
[Issue#2][Функционал приложения] Неккоректно работает каледарь:

### ISSUE THREAD

**Issue by Veleri** [yehormonko/TaskManagerMaven#2]
1. Из даного пункта меню нет выхода. После отображения календаря пользователь должен попадать в главное меню приложения.
    2. Пользователь может ввести некорректную дату: например значение дня больше чем в 2 цифры и т.п.
    3. Когда пользователь вводит некорректную дату, приложение сразу же должно сообщать об ошибке. Сейчас пользователь вводит некорректное значение, например слова, после чего должен ввести значение чч/мм и только затем получает сообщение о некорректном формате даты.
    4. Результат выполнения непонятен: "date FROM is before date TO or they are equal". Приложение должно сообщить, что не найдено ни одной задачи, если найдены, то перечень данных задач.

**Comment by yehorsyrin** [comment]
В комите Last part of Fixes все было исправлено

**Comment by Veleri** [comment]
При создании задачи, а также в календаре пользователь вводит значение даты в формате "print date in format yyyy-MM-dd", затем ему предлагают ввести чч/мм, но если пользователь вводит некорректное значение чч/мм, то снова приходится вводить и саму дату.

**Comment by yehorsyrin** [comment]
Исправлено в Fourth part of Fixes
