### ISSUE TITLE
[Issue#8][Код] Throws Exception

### ISSUE THREAD

**Issue by Veleri** [yehormonko/TaskManagerMaven#20]
В методах, в которых ожидается возникновения ошибки (например создание, редактирование задачи), нужно помечать ошибки, например:
    - throws IOException, ParseException и т.п.

**Comment by yehorsyrin** [comment]
Все методы обрабатывают исключения, не выбрасывают ошибки, так как предусмотрено что если что то будет не так - метод начнет работать заново

**Comment by Veleri** [comment]
Возьмем, к примеру, метод remove() - данный метод удаляет задачи ,в процессе удаления может возникнуть ошибка. Данный метод должен пробрасывать эту ошибку, а в том методе, где вызывался данный метод и должна происходить обработка ошибки.  В самом методе обработки ошибки нет, значит он должен пробросить ее выше.

**Comment by Veleri** [comment]
Доработка сделана, номера коммита нет.
