### ISSUE TITLE
[Issue#11][Код]Удалить лишний код/файлы

### ISSUE THREAD

**Issue by Veleri** [yehormonko/TaskManagerMaven#23]
1.Удалить не использующийся функционал, например закомментированный метод calend().
2.Удалить лишние файлы из репозитория: TaskManeger.uml, TaskManagerMaven.iml и т.п.

**Comment by yehorsyrin** [comment]
В комите Second part of Fixes были удалены все лишние методы и вроде бы я удалил лишние файлы с репозитория
