### ISSUE TITLE
[Issue#3][Функционал приложения] Некорректное значение пункта меню

### ISSUE THREAD

**Issue by Veleri** [yehormonko/TaskManagerMaven#3]
При вводе некорректного значения(буквы, цифры превышающие количество пунктов меню и т.п.) в главном меню, и в любом другом меню, пользователь должен получать сообщение о некорректном знании и т.п.

**Comment by yehorsyrin** [comment]
Исправлено в комите Fixed. При вводе некорректного выводится уведомление и пользователь должен снова вводить значение
