### ISSUE TITLE
[Issue#5][Функционал приложения] Загрузка списка задач при старте приложения

### ISSUE THREAD

**Issue by Veleri** [yehormonko/TaskManagerMaven#5]
Добавить создание нового + загрузку уже существующего списка задач при запуске приложения на выбор пользователя. То есть при старте приложения, пользователь должен выбрать с каким списком он хочет работать:
 - продолжить работу с уже существующим списком;
 - создать новый;
 - загрузить список уже существующий список.

**Comment by yehorsyrin** [comment]
В комите Fixed добавлен новый метод loadFile, который вызывается в конструкторе класса. У пользователя при старте появляется список файлов в папке TaskFiles. Если папки нет - она создается. Если в папке нет файлов - единственным вариантом будет создать новый файл, указать его имя. Если файлы есть - можно выбрать один из них и работать с ним.
