### ISSUE TITLE
[Issue#6][Функционал приложения] Выход из приложения с помощью ключей фразы

### ISSUE THREAD

**Issue by Veleri** [yehormonko/TaskManagerMaven#6]
Добавить в приложение фразу, с помощью которой, пользователь может завершить работу приложения. Например "exit" + сообщать об этой фразе пользователю при старте приложения.

**Comment by yehorsyrin** [comment]
В комите Fixed добавлена ключевая фраза "exit" в методе menu, по которой совершается выход из программы
