### ISSUE TITLE
[Issue#9][Функционал приложения] Кодировка файлов со списками задач

### ISSUE THREAD

**Issue by Veleri** [yehormonko/TaskManagerMaven#9]
Все файлы со списками задач должны быть читаемы. Пользователь должен иметь возможность открыть файлы со списком тасок и увидеть адекватный перечень тасок, с корректной кодировкой.

**Comment by yehorsyrin** [comment]
Исправлено, но не полностью. Файл сохраняется в правильной кодировке, но не открывается стандартно блокнотом. В следующем комите уже будет поправлено, и файл будет сохранятся с расширением *.txt
